# Generated by Django 4.2.2 on 2023-06-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
    ]
