# Generated by Django 4.2.2 on 2023-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_startingbid_listing_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting',
            field=models.BooleanField(default=True),
        ),
    ]
