# Generated by Django 4.2.2 on 2023-06-22 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestBidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestBidderListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
